import { Component } from '@angular/core';
import { Student } from 'src/app/models/student.model';

@Component({
  selector: 'app-student-list',
  templateUrl: './student-list.component.html',
  styleUrls: ['./student-list.component.scss'],
})
export class StudentListComponent {
  students: Student[] = [
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'JBars Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpf: '12345678900',
      createdAt: new Date(),
      enrollment: 'Programação',
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
  ];

  onSubmit(name: string) {}

  onUpdate(item: any) {}

  onDelete(item: any) {}
}
