import { Component } from '@angular/core';
import { Teacher } from 'src/app/models/teacher.mode';

@Component({
  selector: 'app-teacher-list',
  templateUrl: './teacher-list.component.html',
  styleUrls: ['./teacher-list.component.scss'],
})
export class TeacherListComponent {
  teachers: Teacher[] = [
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'Baes Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
    {
      id: 1,
      cpfCnpj: '12345678900',
      createdAt: new Date(),
      specialization: 'Programação',
      experienceYears: 6,
      active: true,
      personData: {
        name: 'John Doe',
        birthDate: new Date('1990-01-01'),
        email: 'johndoe@example.com',
        phone: '54123456789',
        gender: 'masculino',
      },
    },
  ];

  onSubmit(name: string) {}

  onUpdate(item: any) {}

  onDelete(item: any) {}
}
